low effort vibecoded ps5-app-dumper port

diff --git a/ftpdump b/ftpdump
--- a/ftpdump
+++ b/ftpdump
@@ -536,6 +536,54 @@ dump_dir() {
   fi
 }
 
+dump_full_dir() {
+  local dir_count=0
+  local line
+  local i
+
+  # Count number of directories for Wget
+  line=${1#$root}
+  for ((i = 1; i < ${#line}; i++)); do
+    if [[ ${line:$i:1} == "/" ]]; then
+      ((dir_count++))
+    fi
+  done
+  [[ $debug ]] && debug_message \
+    "Dumping directory \"$line\", cutting $dir_count directories."
+
+  # Download directory recursively
+  wget --cut-dirs $dir_count \
+        --no-host-directories --no-parent \
+        --no-verbose --recursive \
+        $wget_options $wget_resume $wget_verbose \
+        --level inf "$1" 2>&1 | \
+    while read -r line; do
+      if [[ $line == *" ->"* ]]; then
+        file_name=${line%\"*}
+        file_name=${file_name#*] -> \"}
+        file_name=${file_name%.listing} # Wget's temporary files
+        file_size=${line%] -> \"*}
+        file_size=${file_size##*[}
+        if [[ $file_name ]]; then
+          echo -e "\e[2K\r$file_name"
+          # Update download progress
+          if [[ $download_progress_enabled ]]; then
+            ((downloaded_bytes += file_size))
+            print_download_progress
+          fi
+        fi
+      elif [[ $verbose && $line != "" ]]; then
+        echo -e "\e[36m$line\e[0m"
+      fi
+    done
+
+  # Abort script if download has failed
+  local result=${PIPESTATUS[0]}
+  if [[ $result -gt 0 ]]; then
+    wget_error $result
+  fi
+}
+
 # Dumps the keystone that belongs to Title ID $1.
 dump_keystone() {
   cd "$output_dir" || abort
@@ -645,6 +693,74 @@ dump_app_data() {
     fi
   fi
 
+  # Merge appmeta (user + system) into sce_sys/.
+  # The mount already provided sce_sys/, so we merge into it.
+  mkdir -p sce_sys || abort
+
+  local src_user_meta="$root/user/appmeta/$1"
+  local src_sys_meta="$root/system_data/priv/appmeta/$1"
+
+  if ftp_file_exists "$src_user_meta"; then
+    echo "Copying user appmeta: $src_user_meta"
+    dump_full_dir "$src_user_meta/"
+  else
+    warning_message "User appmeta not found: $src_user_meta"
+  fi
+
+  if ftp_file_exists "$src_sys_meta"; then
+    echo "Copying system appmeta: $src_sys_meta"
+    dump_full_dir "$src_sys_meta/"
+  else
+    warning_message "System appmeta not found: $src_sys_meta"
+  fi
+
+  # 3. Trophy & UDS via npbind.dat (now under sce_sys/)
+  cd sce_sys || abort
+  mkdir -p trophy2 uds || abort
+
+  local npbind_remote npbind_local=""
+  for npbind_remote in \
+    "${src_sys_meta}/trophy2/npbind.dat" \
+    "${src_sys_meta}/uds/npbind.dat"; do
+    if ftp_file_exists "$npbind_remote"; then
+      npbind_local=$(create_temp_file)
+      curl $curl_options --silent "$npbind_remote" > "$npbind_local" \
+        || curl_error "$npbind_remote"
+      break
+    fi
+  done
+
+  if [[ $npbind_local ]]; then
+    local npwr_id
+    npwr_id=$(read_npwr_id "$npbind_local")
+
+    if [[ $npwr_id ]]; then
+      echo "NPWR ID: $npwr_id"
+
+      local src_trophy="$root/user/trophy2/nobackup/conf/$npwr_id/TROPHY.UCP"
+      if ftp_file_exists "$src_trophy"; then
+        echo "Copying trophy: $src_trophy"
+        dump_file "$src_trophy"
+        mv TROPHY.UCP trophy2/trophy00.ucp || abort
+      else
+        warning_message "Trophy file not found: $src_trophy"
+      fi
+
+      local src_uds="$root/user/np_uds/nobackup/conf/$npwr_id/uds.ucp"
+      if ftp_file_exists "$src_uds"; then
+        echo "Copying UDS: $src_uds"
+        dump_file "$src_uds"
+        mv uds.ucp uds/uds00.ucp || abort
+      else
+        warning_message "UDS file not found: $src_uds"
+      fi
+    else
+      warning_message "Failed to read NPWR ID from $npbind_remote"
+    fi
+  else
+    echo "npbind.dat not found in either location."
+  fi
+
   replace_np_files "$1"
   if [[ -f npbind.dat ]]; then
     replace_encrypted_trophies
@@ -681,10 +797,79 @@ dump_patch_data() {
       dump_and_extract_pkg "$root/mnt/ext0/user/patch/$1/patch.pkg"
     elif ftp_file_exists "$root/mnt/ext1/user/patch/$1/patch.pkg"; then
       dump_and_extract_pkg "$root/mnt/ext1/user/patch/$1/patch.pkg"
-  elif ftp_file_exists "$root/preinst2/patch/$1/app.pkg"; then
-    dump_and_extract_pkg "$root/preinst2/patch/$1/app.pkg"
+    elif ftp_file_exists "$root/preinst2/patch/$1/app.pkg"; then
+      dump_and_extract_pkg "$root/preinst2/patch/$1/app.pkg"
     else
       abort "Could not find FTP file \"patch.pkg\"."
+    fi
+
+
+    # Merge appmeta (user + system) into sce_sys/.
+    # The mount already provided sce_sys/, so we merge into it.
+    mkdir -p sce_sys || abort
+
+    local src_user_meta="$root/user/appmeta/$1"
+    local src_sys_meta="$root/system_data/priv/appmeta/$1"
+
+    if ftp_file_exists "$src_user_meta"; then
+      echo "Copying user appmeta: $src_user_meta"
+      dump_full_dir "$src_user_meta/"
+    else
+      warning_message "User appmeta not found: $src_user_meta"
+    fi
+
+    if ftp_file_exists "$src_sys_meta"; then
+      echo "Copying system appmeta: $src_sys_meta"
+      dump_full_dir "$src_sys_meta/"
+    else
+      warning_message "System appmeta not found: $src_sys_meta"
+    fi
+
+    # 3. Trophy & UDS via npbind.dat (now under sce_sys/)
+    cd sce_sys || abort
+    mkdir -p trophy2 uds || abort
+
+    local npbind_remote npbind_local=""
+    for npbind_remote in \
+      "${src_sys_meta}/trophy2/npbind.dat" \
+      "${src_sys_meta}/uds/npbind.dat"; do
+      if ftp_file_exists "$npbind_remote"; then
+        npbind_local=$(create_temp_file)
+        curl $curl_options --silent "$npbind_remote" > "$npbind_local" \
+          || curl_error "$npbind_remote"
+        break
+      fi
+    done
+
+    if [[ $npbind_local ]]; then
+      local npwr_id
+      npwr_id=$(read_npwr_id "$npbind_local")
+
+      if [[ $npwr_id ]]; then
+        echo "NPWR ID: $npwr_id"
+
+        local src_trophy="$root/user/trophy2/nobackup/conf/$npwr_id/TROPHY.UCP"
+        if ftp_file_exists "$src_trophy"; then
+          echo "Copying trophy: $src_trophy"
+          dump_file "$src_trophy"
+          mv TROPHY.UCP trophy2/trophy00.ucp || abort
+        else
+          warning_message "Trophy file not found: $src_trophy"
+        fi
+
+        local src_uds="$root/user/np_uds/nobackup/conf/$npwr_id/uds.ucp"
+        if ftp_file_exists "$src_uds"; then
+          echo "Copying UDS: $src_uds"
+          dump_file "$src_uds"
+          mv uds.ucp uds/uds00.ucp || abort
+        else
+          warning_message "UDS file not found: $src_uds"
+        fi
+      else
+        warning_message "Failed to read NPWR ID from $npbind_remote"
+      fi
+    else
+      echo "npbind.dat not found in either location."
     fi
 
     replace_np_files "$1"
