Dump base game content to (titleid) instead of (titleid)-app for shadPS4 compatibility + random extra logging

diff --git a/ftpdump b/ftpdump
--- a/ftpdump
+++ b/ftpdump
@@ -602,7 +602,7 @@ dump_app_data() {
 
   cd "$output_dir" || abort
   echo "Dumping $1 app data ($((download_size / 1000000)) MB):"
-  mkdir -p "$1-app" && cd "$1-app" || abort
+  mkdir -p "$1" && cd "$1" || abort
 
   if [[ $pfs_extraction_enabled ]]; then
     dump_and_extract_pfs_image \
@@ -633,7 +633,7 @@ dump_app_data() {
       fi
     else
       warning_message \
-        "App is of type \"remaster\" - editing the file \"$output_dir/$1-app/sce_sys/param.sfo\" may be necessary (e.g. by using the experimental option --fix-remaster)."
+        "App is of type \"remaster\" - editing the file \"$output_dir/$1/sce_sys/param.sfo\" may be necessary (e.g. by using the experimental option --fix-remaster)."
     fi
   fi
 
@@ -1138,7 +1138,7 @@ extract_pkg() {
 dump_and_extract_pkg() {
   local pkg_filename=${1##*/}
 
-  echo "Preparing extraction of $pkg_filename ..."
+  echo "Preparing extraction of $1 ..."
 
   # Test how much PKG data should be downloaded
   [[ $debug ]] && debug_message \
@@ -1784,7 +1784,7 @@ title_id=$(curl $curl_options --silent "$root/mnt/sandbox/pfsmnt/" \
   | grep -Eo -m1 '[A-Z]{4}[0-9]{5}-app0')
 title_id=${title_id%-app0}
 if [[ ! $title_id =~ ^[A-Z]{4}[0-9]{5}$ ]]; then
-  echo "Could not retrieve Title ID. Is the game started?" >&2
+  echo "Could not retrieve Title ID (result: $title_id). Is the game started?" >&2
   clean_exit 1
 fi
 
